site_name: swag documentation
theme:
  name: material
  logo: images/logo_slate.png
  font:
    code: Roboto Mono

  palette:
    scheme: slate
    primary: orange 
    accent: deep orange
    media: "(prefers-color-scheme: dark)"

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en

    - name: Russian 
      link: /ru/
      lang: ru

  homepage: https://github.com/swag-org/swag

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

nav:
  - Hello: 'index.md'
  - Get started: 'get-started.md'
  - HTTPMethod: 'http-method.md'
  - Route: 'http-route.md'
  - Request: 'http-request.md'
  - Response: 'http-response.md'
  - App config: 'swag-app-config.md'
  - Is that framework really?: 'framework-or-lib.md'
